image: Visual Studio 2019
platform: x64
skip_tags: true
environment:
  # Always save the cache because there isn't enough time
  # to build both the dependencies and the collab-vm-server
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  access_token:
    secure: /1wKmhBRo1sCNw9MG237fBihMhCJIMVajWI4BgTKQm39r7J6StfkJFg26TVkK/Qv
pull_requests:
  do_not_increment_build_number: true
install:
  # Clone submodules
  - git submodule update --init --recursive
  # Update vcpkg
  - ps: Remove-Item -Recurse -Force C:\OpenSSL*
  - git -C C:\Tools\vcpkg\ pull
  - C:\Tools\vcpkg\bootstrap-vcpkg.bat
  # Build only release libraries, not debug
  - ps: Add-Content C:\Tools\vcpkg\triplets\$env:PLATFORM-windows-static.cmake "set(VCPKG_BUILD_TYPE release)"
  # GLib is a dependency of cairo that must be dynamically linked
  - ps: (Get-Content C:\Tools\vcpkg\ports\glib\CMakeLists.txt).Replace('${LIBINTL_LIBRARY}', 'unofficial::iconv::libiconv unofficial::iconv::libcharset ${LIBINTL_LIBRARY}') | Set-Content -Encoding Ascii C:\Tools\vcpkg\ports\glib\CMakeLists.txt
  - ps: Add-Content C:\Tools\vcpkg\triplets\$env:PLATFORM-windows-static.cmake "if(PORT MATCHES ""glib"")`n`tset(VCPKG_LIBRARY_LINKAGE dynamic)`n`tset(VCPKG_CRT_LINKAGE dynamic)`nendif()"
  # Install dependencies
  - vcpkg.exe install --triplet %PLATFORM%-windows-static cairo libjpeg-turbo sqlite3 libpng openssl pthreads
  # Upgrade dependencies if they were cached
  - vcpkg.exe upgrade --triplet %PLATFORM%-windows-static --no-dry-run
cache: 
  - C:\Tools\vcpkg\installed\
build_script:
  - ps: Add-Content cmake/MSVCStaticToolchain.cmake 'include("C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake")'
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/install/ -DCMAKE_TOOLCHAIN_FILE=%APPVEYOR_BUILD_FOLDER%/cmake/MSVCStaticToolchain.cmake -DVCPKG_TARGET_TRIPLET=%PLATFORM%-windows-static ..
  - cmake --build . --target install --config RelWithDebInfo
  # Find and copy VNC demo into install directory
  - ps: ls -rec -incl example.exe "$env:APPVEYOR_BUILD_FOLDER/build/" | select -first 1 | cp -dest "$env:APPVEYOR_BUILD_FOLDER/install/vnc-demo.exe"
  # Download and extract web-app
  - cd ..
  - wsl wget https://github.com/Cosmic-Sans/collab-vm-web-app/releases/download/prerelease/web-app.tar.gz
  - wsl tar xfz web-app.tar.gz --directory=install/
artifacts:
  - path: install/
    name: collab-vm-win64
before_deploy:
    # Move the tag to the most recent commit, but delete it first
    # so GitHub updates the timestamp of the release
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git push --delete origin prerelease
  - git tag --force prerelease HEAD
  - git push --force --tags origin prerelease
deploy:
  provider: GitHub
  tag: prerelease
  artifact: collab-vm-win64
  prerelease: true
  draft: false
  force_update: true
  on:
    branch: master
  auth_token:
    secure: /1wKmhBRo1sCNw9MG237fBihMhCJIMVajWI4BgTKQm39r7J6StfkJFg26TVkK/Qv
