image: Visual Studio 2017
platform: x64
environment:
  # Always save the cache because there isn't enough time
  # to build both the dependencies and the collab-vm-server
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
pull_requests:
  do_not_increment_build_number: true
install:
  # Clone submodules
  - git submodule update --init --recursive
  # Update vcpkg
  - git -C C:\Tools\vcpkg\ pull
  - C:\Tools\vcpkg\bootstrap-vcpkg.bat
  # Install dependencies
  - vcpkg.exe install --triplet %PLATFORM%-windows cairo libjpeg-turbo libodb libodb-sqlite libpng openssl pthreads
  - ps: |
      if (-not (Test-Path C:\Tools\odb-2.4.0-i686-windows\))
      {
        # Download and extract the ODB compiler
        Start-FileDownload -Url 'https://www.codesynthesis.com/download/odb/2.4/odb-2.4.0-i686-windows.zip' -FileName 'C:\Tools\odb-2.4.0-i686-windows.zip'
        7z x C:\Tools\odb-2.4.0-i686-windows.zip -oC:\Tools\ 
      }
cache: 
  - C:\Tools\vcpkg\
  - C:\Tools\odb-2.4.0-i686-windows\
build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/install/ -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=%PLATFORM%-windows -DBOOST_ROOT=C:/Libraries/boost_1_67_0/ -DBoost_USE_STATIC_LIBS=ON -DBoost_USE_STATIC_RUNTIME=OFF -DODB-COMPILER_ROOT=C:/Tools/odb-2.4.0-i686-windows/ ..
  - cmake --build . --target install --config RelWithDebInfo
artifacts:
  - path: install/
    name: collab-vm-server
