name: CollabVM Server 2 CI

on: [push, pull_request]

jobs:
  windows_x64:
    runs-on: windows-latest
    steps:
      - name: Build
        shell: cmd
        run: |
          mkdir build
          echo test > build\hello
      - name: Upload Release Asset
        uses: marvinpinto/action-automatic-releases@v0.2.2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: prerelease
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          tag: prerelease
          artifact: build/hello
